# 로또 번호 추출기

- 로또 당첨번호(보너스 번호), 회차, 추첨일자, 1등 당첨자수, 당첨금액, 판매금액 크롤링 코드

In [1]:
def lotto_num(n,m):   # n : 시작회차, m : 끝 회차
    # 1. 필요한 패키지를 가져옵니다.
    import urllib.request
    from bs4 import BeautifulSoup
    from selenium import webdriver
    from selenium.webdriver.common.keys import Keys
    import time
    import re  # 데이터 정제 전문 모듈
    import pandas as pd

    #2. 크롬 드라이버의 위치를 지정합니다. 

    driver = webdriver.Chrome("chromedriver.exe")   # 크롬 드라이버 위치 설정

    #3. 페이지 번호를 반복하면서 상세 url 을 가져오는 반복문
    turn = []
    day = []
    num1 = []
    num2 = []
    num3 = []
    num4 = []
    num5 = []
    num6 = []
    num7 = []
    people = []
    money =[]
    tot=[]

    for i in range(n,m+1):

        time.sleep(1)

        list_url = "https://www.dhlottery.co.kr/gameResult.do?method=byWin&drwNo=" + str(i)

        driver.get(list_url)

        #4. 지금 현재 보이는 페이지의 html 코드를 가져옵니다.
        time.sleep(1)
        html = driver.page_source

        #5. html 코드를 뷰티플 스프 모듈의 함수를 이용해서 검색할 수 있도록 합니다.
        soup = BeautifulSoup( html, "html.parser")  # html.parser 또는 lxml 로 하면 됩니다. 

        # 회차
        no = soup.select('div.win_result > h4 > strong')
        # 추첨일
        date = soup.select('div.win_result > p')
        # 당첨 번호
        number = soup.select('div.num.win > p > span')
        # 보너스 번호
        bonus = soup.select('div.num.bonus > p > span')
        # 1등 당첨금액, 1등 당첨개수
        td = soup.select('td')        
        # 총 판매금액
        total = soup.select('ul.list_text_common > li > strong')

        numbers = []
        for j in number:
            numbers.append(int(j.text))

        #6. 각각 리스트에 담기
        time.sleep(1)

        turn.append(no[0].text)
        day.append(re.sub('[()추첨 ]', '', date[0].text))
        num1.append(numbers[0])
        num2.append(numbers[1])
        num3.append(numbers[2])
        num4.append(numbers[3])
        num5.append(numbers[4])
        num6.append(numbers[5])
        num7.append(bonus[0].text)
        people.append(td[2].text)
        money.append(td[3].text)
        tot.append(total[0].text)

    lotto = pd.DataFrame({
        "회차" : turn,
        "일자" : day,
        "번호1" : num1,
        "번호2" : num2,
        "번호3" : num3,
        "번호4" : num4,
        "번호5" : num5,
        "번호6" : num6,
        "보너스" : num7,
        "1등 당첨자수" : people,
        "1등 당첨금액" : money,
        "총 판매금액" : tot
        })
    
    lotto.to_csv('lotto_num_최신.csv', index=False)   # 파일명 및 저장 위치 설정
    
    print("수집이 완료되었습니다.")
    
    return lotto

In [26]:
lotto_num(1,1054)

C:\Users\kkn84\AppData\Local\Temp\ipykernel_25276\817344515.py:13: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("d:\\data\\chromedriver.exe")

수집이 완료되었습니다.

,회차,일자,번호1,번호2,번호3,번호4,번호5,번호6,보너스,1등 당첨자수,1등 당첨금액,총 판매금액
0,1회,2002년12월07일,10,23,29,33,37,40,16,0,0원,"3,681,782,000원"
1,2회,2002년12월14일,9,13,21,25,32,42,2,1,"2,002,006,800원","4,904,274,000원"
2,3회,2002년12월21일,11,16,19,21,27,31,30,1,"2,000,000,000원","4,729,342,000원"
3,4회,2002년12월28일,14,27,30,31,40,42,2,0,0원,"5,271,464,000원"
4,5회,2003년01월04일,16,24,29,40,41,42,3,0,0원,"6,277,102,000원"
...,...,...,...,...,...,...,...,...,...,...,...,...
1049,1050회,2023년01월14일,6,12,31,35,38,43,17,17,"1,535,083,280원","108,072,602,000원"
1050,1051회,2023년01월21일,21,26,30,32,33,35,44,18,"1,669,558,480원","119,243,907,000원"
1051,1052회,2023년01월28일,5,17,26,27,35,38,1,11,"2,341,682,762원","107,565,461,000원"
1052,1053회,2023년02월04일,22,26,29,30,34,45,15,7,"4,090,367,411원","113,721,665,000원"
1053,1054회,2023년02월11일,14,19,27,28,30,45,33,9,"3,147,925,709원","113,660,567,000원"

In [2]:
lotto_num(1055,1057)

C:\Users\kkn84\AppData\Local\Temp\ipykernel_29324\2318098093.py:13: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("chromedriver.exe")   # 크롬 드라이버 위치 설정

수집이 완료되었습니다.

,회차,일자,번호1,번호2,번호3,번호4,번호5,번호6,보너스,1등 당첨자수,1등 당첨금액,총 판매금액
0,1055회,2023년02월18일,4,7,12,14,22,33,31,11,"2,362,815,205원","112,488,256,000원"
1,1056회,2023년02월25일,13,20,24,32,36,45,29,14,"1,969,662,456원","113,279,615,000원"
2,1057회,2023년03월04일,8,13,19,27,40,45,12,17,"1,616,069,714원","112,523,887,000원"